name: Build and Deploy to Azure Container Registry

on:
  push:
    branches: [ main, dev, 'devops/docker']
  pull_request:
    branches: [ main, dev, 'feature/**', 'devops/docker' ]

env:
  REGISTRY: hrmgmtregistry123.azurecr.io
  IMAGE_NAME: hrmgmtapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest
